# Generated by Django 5.0.3 on 2024-06-20 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbvapp', '0004_alter_company_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='car_image',
            field=models.ImageField(blank=True, null=True, upload_to='cars/'),
        ),
    ]
