# Generated by Django 5.0.3 on 2024-06-20 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbvapp', '0005_products_car_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='rate',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
